# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField()),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
            ],
        ),
    ]
