# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='placeType',
            field=models.CharField(default='final', max_length=10),
        ),
    ]
