# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models
#import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('ContactPerson', models.CharField(max_length=30)),
                ('Desig', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('Fax', models.CharField(max_length=20)),
                ('Website', models.URLField()),
                ('Email', models.EmailField(max_length=254)),
                ('BriefCompanyProfile', models.CharField(max_length=100)),
                ('FinalPosOff', models.CharField(max_length=50)),
                ('FinalNoOfVac', models.IntegerField()),
                ('FinalJobLoc', models.CharField(max_length=50)),
                ('FinalBenefits', models.CharField(max_length=50)),
                ('FinalSelectionProc', models.CharField(max_length=50)),
                ('FinalOtherSpecify', models.CharField(default='NA', max_length=50)),
                ('InternPosOff', models.CharField(max_length=49)),
                ('InternNoOfVac', models.IntegerField()),
                ('InternJobLoc', models.CharField(max_length=50)),
                ('InternBenefits', models.CharField(max_length=50)),
                ('InternSelectionProc', models.CharField(max_length=50)),
                ('InternOtherSpecify', models.CharField(default='NA', max_length=50)),
                ('FacilityReq', models.CharField(max_length=50)),
            ],
        ),
    ]
