# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-15 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='FinalOtherSpecify',
        ),
        migrations.RemoveField(
            model_name='company',
            name='InternOtherSpecify',
        ),
    ]
