# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20171115_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Fax',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
